import {defaults,calculate,marginal,validate} from './calculator.js';
const KEY='poe2-damage-calculator-v1';
let state=structuredClone(defaults),history=[],storageOK=true,valid=true;
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2}).format(n),pct=n=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:4}).format(n);
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);validate(saved.state);state=saved.state;history=Array.isArray(saved.history)?saved.history.filter(h=>{try{validate(h.state);return typeof h.date==='string'&&typeof h.id==='string';}catch{return false;}}).slice(0,50):[];}}catch{storageOK=false;$('#error').textContent='本地记录不可用或已损坏，已载入默认配置。';}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({state,history}));storageOK=true;}catch{storageOK=false;}$('#save-status').textContent=storageOK?'已自动保存':'存储不可用，请勿关闭页面';}
function fill(){for(const key of ['base','added','inc','rate','crit','bonus'])$('#form').elements[key].value=state[key];renderMore();update();}
function renderMore(){const list=$('#more-list');list.replaceChildren();state.more.forEach((m,i)=>{const row=el('div','more-row'),name=el('input'),wrap=el('span','input-wrap'),value=el('input'),remove=el('button','remove','×');name.type='text';name.value=m.name;name.maxLength=80;name.setAttribute('aria-label',`倍率 ${i+1} 名称`);name.addEventListener('input',()=>{m.name=name.value;update();});value.type='number';value.min='-100';value.step='any';value.required=true;value.value=m.value;value.setAttribute('aria-label',`倍率 ${i+1} 百分比`);value.addEventListener('input',()=>{m.value=value.valueAsNumber;update();});remove.type='button';remove.setAttribute('aria-label',`删除倍率 ${i+1}`);remove.addEventListener('click',()=>{state.more.splice(i,1);renderMore();update();});wrap.append(value,el('span','','%'));row.append(name,wrap,remove);list.append(row);});$('#add-more').disabled=state.more.length>=50;}
function update(){try{if(!$('#form').checkValidity())throw Error('请填写有效数字：暴击率为 0–100%，inc 和 more 不低于 −100%。');const r=calculate(state);const gains=marginal(state);valid=true;$('#error').textContent='';for(const k of ['dps','hit','average'])$('#'+k).textContent=fmt(r[k]);const list=$('#gains');list.replaceChildren();const max=Math.max(1,...gains.map(g=>g.percent??0));gains.forEach(g=>{const row=el('div','gain'),left=el('div'),right=el('div','gain-value',g.percent===null?'—':`+${pct(g.percent)}%`),bar=el('div','bar'),ink=el('i');left.append(el('div','gain-title',g.name),el('small','',g.unit));ink.style.width=`${Math.max(0,(g.percent??0)/max*100)}%`;bar.append(ink);left.append(bar);right.append(el('small','',`+${fmt(g.delta)} DPS`));row.append(left,right);list.append(row);});persist();}catch(e){valid=false;$('#error').textContent=e.message;for(const k of ['dps','hit','average'])$('#'+k).textContent='—';$('#gains').replaceChildren();$('#save-status').textContent='当前输入尚未保存';}$('#save').disabled=!valid;}
$('#form').addEventListener('submit',e=>e.preventDefault());for(const key of ['base','added','inc','rate','crit','bonus'])$('#form').elements[key].addEventListener('input',e=>{state[key]=e.target.valueAsNumber;update();});
$('#add-more').addEventListener('click',()=>{if(state.more.length>=50)return;state.more.push({name:`独立倍率 ${state.more.length+1}`,value:0});renderMore();update();});
$('#reset').addEventListener('click',()=>{state=structuredClone(defaults);fill();});
$('#save').addEventListener('click',()=>{if(!valid)return;history.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),state:structuredClone(state)});history=history.slice(0,50);persist();renderHistory();});
function renderHistory(){const list=$('#history-list');list.replaceChildren();if(!history.length){list.append(el('div','empty','还没有保存的结果。保存一组配置，留给下一次比较。最多保留最近 50 条。'));return;}history.forEach(h=>{const row=el('div','history-entry'),record=el('div','record'),load=el('button','','载入配置'),remove=el('button','quiet','删除');record.append(el('strong','',`${fmt(calculate(h.state).dps)} DPS`),el('small','',`${new Date(h.date).toLocaleString('zh-CN')} · 基础 ${fmt(h.state.base)} · inc ${h.state.inc}% · ${h.state.more.length} 条倍率`));load.addEventListener('click',()=>{state=structuredClone(h.state);fill();$('#form').scrollIntoView({block:'start'});});remove.addEventListener('click',()=>{history=history.filter(item=>item.id!==h.id);persist();renderHistory();});row.append(record,load,remove);list.append(row);});}
fill();renderHistory();
